name: Auto Sync Develop

on:
  push:
    branches:
      - stage

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  merge:
    name: Merge to Develop
    # The job runs only if the pull request is merged and it's from 'changesets-release/stage' branch
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Merge staging -> develop
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: develop
          github_token: ${{ secrets.GITHUB_TOKEN }}
