name: Auto Sync Develop

on:
  push:
    branches:
      - stage

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  merge:
    name: Merge to Develop
    # The job runs only if we're not merging from develop branch.
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Check if push is from develop branch
        id: check
        run: |
          git fetch origin develop:develop
          echo "FROM_DEVELOP=$(git merge-base --is-ancestor ${{ github.event.before }} develop && echo 'true' || echo 'false')" >> $GITHUB_OUTPUT
      - name: Open Pull Request
        if: ${{ steps.check.outputs.FROM_DEVELOP == 'false' }}
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: develop
          branch: stage
          title: 'Merge stage into develop'
          body: 'This is an automated pull request to merge changes from stage into develop.'
