name: Auto Sync Develop

on:
  pull_request:
    types:
      - closed
    branches:
      - stage

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  merge:
    name: Merge to Develop
    # The job runs only if the pull request is merged and it's from 'changesets-release/stage' branch
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: develop
      - name: Pull Latest Changes
        run: |
          git pull origin stage
          git branch -a
          git log remotes/origin/develop..remotes/origin/stage
      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Sync Develop with Stage
          branch: develop
